name: Builds
on: push

jobs:
  build:
    name: Build #${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Do we want the build to continue when failing or not?
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        target: ["appbundle"] #, "ios --no-codesign" 
    steps:
    - name: Checkout Repository code
      uses: actions/checkout@v3.3.0
      
#     - name: Set up JDK 11
#       uses: actions/setup-java@v3.10.0
#       with:
#         distribution: 'temurin'
#         #cache: 'gradle'
#         java-version: '11.x'
#         #java-package: jre

#     - name: Set up Flutter
#       uses: subosito/flutter-action@v1
#       with:
#         # Default is stable
#         channel: 'stable'
#         flutter-version: '3.7.x'
#         architecture: x64
#     #- run: flutter config --enable-linux-desktop #--enable-macos-desktop 
#     - run: flutter doctor -v

#     - run: flutter pub get
#     - run: flutter build ${{ matrix.target }}